session4 HW 1
celestfradel/ASPNetCoreMasters pull request #4
Opened 2021-09-26 13:26 UTC by celestfradel

session4 HW For Review

2021-09-26 15:53 UTC, jegtugado requested changes
Hi. Minor change needed

2021-09-26 15:53 UTC, jegtugado commented on ASPNetCoreMasters.Api/Controllers/ItemsController.cs
> +        public IActionResult Put(int id, [FromBody] ItemCreateBindingModel itemUpdateModel)
ItemCreateBindingModel should work here but I would recommend you to follow the homework and create an ItemUpdateBindingModel for the purpose of updating the item

2021-09-27 06:28 UTC, celestfradel commented on ASPNetCoreMasters.Api/Controllers/ItemsController.cs
> +        public IActionResult Put(int id, [FromBody] ItemCreateBindingModel itemUpdateModel)
updated to use the ItemUpdateBindingModel

2021-09-27 12:25 UTC, jegtugado approved these changes

2021-09-27 12:26 UTC, merged