Session5 HW
celestfradel/ASPNetCoreMasters pull request #5
Opened 2021-09-26 15:04 UTC by celestfradel

session 5 HW. For Review. Thank you

2021-09-27 12:32 UTC, jegtugado requested changes
Hi sir, minor changes needed.

2021-09-27 12:32 UTC, jegtugado commented on Repositories/ItemRepository.cs
> +            _dataContext.Items.Add(item);
Can you modify this to be able to handle both add and update scenarios?

2021-09-27 12:32 UTC, jegtugado commented on Services/ItemService.cs
> +            var itemToUpdate = _itemRepository.All().Where(x => x.Id == itemDto.Id).SingleOrDefault();
please use IItemRepository.Save method for updating

2021-09-27 12:32 UTC, jegtugado commented on ASPNetCoreMasters.Api/Startup.cs
> +            services.AddScoped<DataContext>();
We recommend using Singleton lifetime for the datacontext so you can verify if the Item Add or Update worked

2021-09-29 08:59 UTC, celestfradel commented on ASPNetCoreMasters.Api/Startup.cs
> +            services.AddScoped<DataContext>();
updated Session5 HW for the changes. For Review

2021-09-29 10:58 UTC, jegtugado approved these changes

2021-09-29 10:58 UTC, merged